set(DEBUG_ENABLE false)
set(CMAKE_VERBOSE_MAKEFILE OFF)
set(NRF_TARGET "nrf51")
set(SOFTDEVICE "s110")
set(ARM_NONE_EABI_TOOLCHAIN_PATH "D:/Programs/ArmEmbededToolchain")
set(NRF5_SDK_PATH "D:/Programs/nrf51/nRF51_SDK_10.0.0")
set(MERGEHEX_PATH "mergehex.exe")
set(OPENOCD_PATH "C:/Users/Stepan/OpenOCD/bin/openocd.exe")